version: '3.8'

services:
  frontend:
    build:
      context: ./annubisFrontV4
    ports:
      - "80:80"
    networks:
      - mynetwork

  backend:
    build:
      context: ./annubisBackV4
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/3dprints
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=8549BSCjavi!
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 8549BSCjavi!
      MYSQL_DATABASE: 3dprints
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
    driver: local
